services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
